version: "3"
services:
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "5002:5002"

  shipping-service:
    build:
      context: ./shipping-service
    ports:
      - "5001:5001"

  users-service:
    build:
      context: ./users-service
    ports:
      - "5008:5008"

  billing-service:
    build:
      context: ./billing-service
    ports:
      - "5000:5000"
